"""empty message

Revision ID: 27a081b1d75f
Revises: 18853a80145e
Create Date: 2025-09-01 01:48:12.054338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27a081b1d75f'
down_revision: Union[str, Sequence[str], None] = '18853a80145e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asic_models', sa.Column('get_coin', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asic_models', 'get_coin')
    # ### end Alembic commands ###
